### Register students
POST http://localhost:3001/api/register
Content-Type: application/json

{
  "teacher": "teacherken@gmail.com",
  "students": [
    "commonstudent1@gmail.com",
    "commonstudent2@gmail.com",
    "studentbob@gmail.com",
    "studenthon@gmail.com",
    "studentjon@gmail.com"
  ]
}

### Get common students (Single teacher)
GET http://localhost:3001/api/commonstudents?teacher=teacherken@gmail.com
Content-Type: application/json

### Get common students (Multiple teachers)
GET http://localhost:3001/api/commonstudents?teacher=teacherken@gmail.com&teacher=teacherjoe@gmail.com
Content-Type: application/json

### Suspend a student
POST http://localhost:3001/api/suspend
Content-Type: application/json

{
  "student": "studentmike@gmail.com"
}
### Send notification (With Teacher having No students)
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "teacheremma@gmail.com",
  "notification": "Hello students!"
}

### Send notification (With Teacher but No students passed)
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "teacheremma@gmail.com",
  "notification": "Hello students! @studentbob@gmail.com @studenthon@gmail.com"
}

### Send notification (With mentioned students not exist)
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "teacherken@gmail.com",
  "notification": "Hello students! @studentjai@gmail.com @studenthon@gmail.com"
}

### Send notification with non-existent @mentioned student
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "teacherjoe@gmail.com",
  "notification": "Hello @notExistentStudent@gmail.com"
}

### Send notification (Missing fields)
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "teacherken@gmail.com"
}

### Send notification (Non-existent teacher)
POST http://localhost:3001/api/retrievefornotifications
Content-Type: application/json

{
  "teacher": "nonexistent@gmail.com",
  "notification": "Hello students!"
}
